name: expressdelivery
description: Aplicación Express Delivery multiplataforma creada con Flutter.
publish_to: "none"
version: 1.5.77+118

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.3
  flutter_map: ^8.3.2
  latlong2: ^0.10.1
  http: ^1.5.0
  geolocator: ^14.1.1
  firebase_core: ^4.15.0
  firebase_messaging: ^16.7.0
  flutter_local_notifications: ^20.1.0
  url_launcher: ^6.3.2
  package_info_plus: ^10.2.1
  shorebird_code_push: ^2.0.7
  terminate_restart: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: 0.14.4

flutter:
  uses-material-design: true
  assets:
    - shorebird.yaml
    - assets/branding/express_app_icon.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/branding/express_app_icon.png"
  min_sdk_android: 21
