-- Express Delivery - initial Supabase schema
-- Applied to project cdgemtkumzxlbhdgxlwn

create schema if not exists app_private;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  role text not null default 'customer' check (role in ('customer','driver','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.profiles(id) on delete restrict,
  driver_id uuid references public.profiles(id) on delete set null,
  pickup_address text not null,
  delivery_address text not null,
  notes text,
  status text not null default 'pending' check (status in ('pending','accepted','picked_up','in_transit','delivered','cancelled')),
  total numeric(12,2) not null default 0 check (total >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_status_history (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  status text not null check (status in ('pending','accepted','picked_up','in_transit','delivered','cancelled')),
  changed_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now()
);

create index if not exists orders_customer_id_idx on public.orders(customer_id);
create index if not exists orders_driver_id_idx on public.orders(driver_id);
create index if not exists orders_status_idx on public.orders(status);

alter table public.profiles enable row level security;
alter table public.orders enable row level security;
alter table public.order_status_history enable row level security;
