-- QA load lab: synthetic drivers/requests isolated inside audit sandbox.
-- Production users keep current limits and notification behavior.

create table if not exists public.audit_load_test_runs (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.audit_test_groups(id) on delete cascade,
  label text not null default 'Iquique load test',
  city text not null default 'Iquique',
  center_latitude numeric not null,
  center_longitude numeric not null,
  radius_km numeric not null default 3 check (radius_km > 0 and radius_km <= 20),
  driver_count integer not null default 0 check (driver_count >= 0 and driver_count <= 500),
  request_count integer not null default 0 check (request_count >= 0 and request_count <= 500),
  status text not null default 'creating'
    check (status in ('creating','active','cleaning','cleaned','failed')),
  created_by uuid references auth.users(id) on delete set null,
  metrics jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  cleaned_at timestamptz
);

create table if not exists public.audit_load_test_entities (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.audit_load_test_runs(id) on delete cascade,
  entity_type text not null check (entity_type in ('driver','ride_request')),
  user_id uuid references auth.users(id) on delete cascade,
  ride_request_id uuid references public.ride_requests(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint audit_load_test_entity_shape check (
    (entity_type='driver' and user_id is not null and ride_request_id is null)
    or
    (entity_type='ride_request' and ride_request_id is not null)
  )
);

create index if not exists audit_load_test_runs_status_idx
  on public.audit_load_test_runs(status, created_at desc);
create index if not exists audit_load_test_entities_run_idx
  on public.audit_load_test_entities(run_id, entity_type);
create index if not exists audit_load_test_entities_user_idx
  on public.audit_load_test_entities(user_id)
  where user_id is not null;
create index if not exists audit_load_test_entities_ride_idx
  on public.audit_load_test_entities(ride_request_id)
  where ride_request_id is not null;

alter table public.audit_load_test_runs enable row level security;
alter table public.audit_load_test_entities enable row level security;

revoke all on table public.audit_load_test_runs from anon, authenticated;
revoke all on table public.audit_load_test_entities from anon, authenticated;
grant all on table public.audit_load_test_runs to service_role;
grant all on table public.audit_load_test_entities to service_role;

create or replace function public.admin_audit_load_state()
returns jsonb
language plpgsql
stable security definer
set search_path=public
as $$
declare
  v_runs jsonb;
begin
  if not public.is_admin() then
    raise exception 'No autorizado';
  end if;

  select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc),'[]'::jsonb)
  into v_runs
  from (
    select
      r.*,
      coalesce((
        select count(*) from public.audit_load_test_entities e
        where e.run_id=r.id and e.entity_type='driver'
      ),0)::int as tracked_drivers,
      coalesce((
        select count(*) from public.audit_load_test_entities e
        where e.run_id=r.id and e.entity_type='ride_request'
      ),0)::int as tracked_requests
    from public.audit_load_test_runs r
    order by r.created_at desc
    limit 20
  ) x;

  return jsonb_build_object('runs',v_runs);
end;
$$;

revoke all on function public.admin_audit_load_state() from public, anon;
grant execute on function public.admin_audit_load_state() to authenticated;

-- Load-test requests are intentionally silent: they exercise Realtime, map,
-- filtering and rendering without generating a push storm.
create or replace function public.notify_available_ride_to_drivers()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_driver record;
  v_lock_driver uuid;
begin
  if new.status <> 'searching' then
    return new;
  end if;

  if left(coalesce(new.pickup_address,''), 9) = '[LOADTEST' then
    return new;
  end if;

  if tg_op = 'UPDATE' then
    if old.status = 'searching'
       and old.expires_at is not distinct from new.expires_at
       and old.proposed_fare is not distinct from new.proposed_fare then
      return new;
    end if;
  end if;

  if new.scheduled_for is not null
     and new.scheduled_for > now() + interval '30 minutes' then
    return new;
  end if;

  for v_driver in
    select
      dp.id,
      case
        when new.pickup_latitude is null
          or new.pickup_longitude is null
          or dp.latitude is null
          or dp.longitude is null
        then null::double precision
        else
          6371 * acos(
            least(1, greatest(-1,
              cos(radians(new.pickup_latitude::double precision))
              * cos(radians(dp.latitude::double precision))
              * cos(
                  radians(dp.longitude::double precision)
                  - radians(new.pickup_longitude::double precision)
                )
              + sin(radians(new.pickup_latitude::double precision))
              * sin(radians(dp.latitude::double precision))
            ))
          )
      end as distance_km
    from public.driver_profiles dp
    where dp.approval_status = 'approved'
      and dp.online_status = 'online'
      and dp.id <> new.passenger_id
      and public.same_operational_scope(dp.id, new.passenger_id)
      and (
        new.pickup_latitude is null
        or new.pickup_longitude is null
        or dp.latitude is null
        or dp.longitude is null
        or (
          6371 * acos(
            least(1, greatest(-1,
              cos(radians(new.pickup_latitude::double precision))
              * cos(radians(dp.latitude::double precision))
              * cos(
                  radians(dp.longitude::double precision)
                  - radians(new.pickup_longitude::double precision)
                )
              + sin(radians(new.pickup_latitude::double precision))
              * sin(radians(dp.latitude::double precision))
            ))
          )
        ) <= 10
      )
    order by distance_km nulls last, dp.updated_at desc nulls last
  loop
    v_lock_driver := null;

    insert into public.driver_request_push_locks (
      driver_id, ride_request_id, locked_until, updated_at
    )
    values (
      v_driver.id, new.id, now() + interval '15 seconds', now()
    )
    on conflict (driver_id)
    do update set
      ride_request_id = excluded.ride_request_id,
      locked_until = excluded.locked_until,
      updated_at = now()
    where public.driver_request_push_locks.locked_until <= now()
    returning driver_id into v_lock_driver;

    if v_lock_driver is null then continue; end if;

    insert into public.notifications(user_id, title, body, type)
    values(
      v_driver.id,
      'Nueva solicitud disponible',
      'Tienes una nueva solicitud cercana. Abre Express para verla.',
      'ride_request'
    );
  end loop;

  return new;
end;
$$;

-- Audit users may render a larger synthetic map. Production stays capped at 16.
create or replace function public.nearby_online_driver_markers(
  p_lat numeric,
  p_lng numeric,
  p_radius_km numeric default 5,
  p_vehicle_type text default null
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_result jsonb;
  v_requested text := nullif(lower(trim(coalesce(p_vehicle_type, ''))), '');
  v_uid uuid := auth.uid();
  v_audit boolean := false;
  v_limit integer := 16;
begin
  if v_uid is null or not public.is_account_active() then
    raise exception 'No autorizado';
  end if;

  select exists(
    select 1
    from public.audit_test_group_members m
    join public.audit_test_groups g on g.id=m.group_id
    where m.user_id=v_uid and m.enabled=true and g.active=true
  ) into v_audit;

  if v_audit then v_limit := 250; end if;

  with candidates as (
    select
      round(dp.latitude::numeric, 3) as latitude,
      round(dp.longitude::numeric, 3) as longitude,
      coalesce(
        (
          select dv.vehicle_type
          from public.driver_vehicles dv
          where dv.driver_id = dp.id
            and dv.is_active = true
          order by dv.updated_at desc
          limit 1
        ),
        case
          when lower(coalesce(dp.vehicle_summary,'')) like '%moto%' then 'motorcycle'
          when lower(coalesce(dp.vehicle_summary,'')) like '%xl%' then 'xl'
          else 'car'
        end
      ) as vehicle_type,
      (
        6371 * acos(
          least(1, greatest(-1,
            cos(radians(p_lat::double precision))
            * cos(radians(dp.latitude::double precision))
            * cos(radians(dp.longitude::double precision) - radians(p_lng::double precision))
            + sin(radians(p_lat::double precision))
            * sin(radians(dp.latitude::double precision))
          ))
        )
      ) as distance_km
    from public.driver_profiles dp
    where dp.approval_status = 'approved'
      and dp.online_status = 'online'
      and dp.latitude is not null
      and dp.longitude is not null
      and public.same_operational_scope(v_uid, dp.id)
  )
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'latitude', latitude,
        'longitude', longitude,
        'vehicle_type', vehicle_type,
        'distance_km', round(distance_km::numeric, 1)
      )
      order by distance_km
    ),
    '[]'::jsonb
  )
  into v_result
  from (
    select *
    from candidates
    where distance_km <= greatest(0.5, least(coalesce(p_radius_km, 5), 20))
      and (v_requested is null or vehicle_type = v_requested)
    order by distance_km
    limit v_limit
  ) q;

  return v_result;
end;
$$;

-- Audit drivers may receive up to 250 synthetic requests for load testing.
-- Production remains governed by app_settings and capped at 100.
create or replace function public.available_ride_requests_for_driver()
returns jsonb
language plpgsql
stable security definer
set search_path=public
as $$
declare
  v_uid uuid := auth.uid();
  v_result jsonb;
  v_scheduled_before integer := 30;
  v_visible_seconds integer := 180;
  v_max_visible integer := 20;
  v_radius numeric := 15;
  v_lat numeric;
  v_lng numeric;
  v_audit boolean := false;
  v_limit integer := 20;
begin
  if v_uid is null or not public.is_account_active() then
    raise exception 'No autorizado';
  end if;

  if not public.is_approved_online_driver(v_uid) then
    return '[]'::jsonb;
  end if;

  select
    coalesce(scheduled_publish_before_minutes,30),
    coalesce(request_visible_seconds,180),
    coalesce(max_visible_requests_driver,20),
    coalesce(max_driver_request_radius_km,15)
  into v_scheduled_before,v_visible_seconds,v_max_visible,v_radius
  from public.app_settings
  where id=true;

  select exists(
    select 1
    from public.audit_test_group_members m
    join public.audit_test_groups g on g.id=m.group_id
    where m.user_id=v_uid and m.enabled=true and g.active=true
  ) into v_audit;

  v_limit := case
    when v_audit then 250
    else least(greatest(v_max_visible,1),100)
  end;

  select latitude,longitude
  into v_lat,v_lng
  from public.driver_profiles
  where id=v_uid
  limit 1;

  select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at asc),'[]'::jsonb)
  into v_result
  from (
    select r.*
    from public.ride_requests r
    where r.status in ('searching','offers_received')
      and r.expires_at > now()
      and r.passenger_id <> v_uid
      and public.same_operational_scope(r.passenger_id, v_uid)
      and (
        r.scheduled_for is null
        or r.scheduled_for <=
          now() + make_interval(mins => least(greatest(v_scheduled_before,5),1440))
      )
      and (
        r.scheduled_for is not null
        or r.created_at >
          now() - make_interval(secs => least(greatest(v_visible_seconds,30),1800))
      )
      and exists (
        select 1
        from public.service_catalog c
        where c.service_key=r.category
          and c.enabled=true
          and c.driver_visible=true
      )
      and (
        v_lat is null
        or v_lng is null
        or r.pickup_latitude is null
        or r.pickup_longitude is null
        or (
          111.195 * sqrt(
            power((r.pickup_latitude - v_lat)::double precision,2) +
            power(
              ((r.pickup_longitude - v_lng)::double precision) *
              cos(radians(((r.pickup_latitude + v_lat) / 2)::double precision)),
              2
            )
          )
        ) <= least(greatest(v_radius,1),100)
      )
    order by r.created_at asc
    limit v_limit
  ) x;

  return v_result;
end;
$$;
