
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;
grant usage on schema private to service_role;

create table if not exists public.driver_subscription_plans (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  amount numeric(12,2) not null check (amount >= 0),
  days integer not null check (days > 0),
  currency_code text not null default 'BOB',
  benefits jsonb not null default '[]'::jsonb check (jsonb_typeof(benefits)='array'),
  active boolean not null default true,
  sort_order integer not null default 0,
  zone_key text not null default 'trinidad',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.driver_subscription_settings (
  id boolean primary key default true check (id),
  enabled boolean not null default true,
  enforce_access boolean not null default false,
  provider text not null default 'veripagos',
  provider_enabled boolean not null default false,
  qr_validity text not null default '0/00:15',
  zone_key text not null default 'trinidad',
  updated_at timestamptz not null default now(),
  updated_by uuid
);

insert into public.driver_subscription_settings(id) values(true)
on conflict(id) do nothing;

insert into public.driver_subscription_plans
(code,name,amount,days,currency_code,benefits,active,sort_order,zone_key)
values
('daily','Diario',10,1,'BOB','["Acceso a solicitudes de viajes","Ofertar tu tarifa","Soporte Express"]'::jsonb,true,10,'trinidad'),
('weekly','Semanal',20,7,'BOB','["Acceso a solicitudes de viajes","Ofertar tu tarifa","Soporte Express"]'::jsonb,true,20,'trinidad'),
('biweekly','Quincenal',30,15,'BOB','["Acceso a solicitudes de viajes","Ofertar tu tarifa","Soporte Express"]'::jsonb,true,30,'trinidad'),
('monthly','Mensual',40,30,'BOB','["Acceso a solicitudes de viajes","Ofertar tu tarifa","Soporte Express"]'::jsonb,true,40,'trinidad')
on conflict(code) do nothing;

create table if not exists public.driver_subscription_payments (
  id bigint generated by default as identity primary key,
  driver_id uuid not null references public.driver_profiles(id) on delete cascade,
  plan_id bigint not null references public.driver_subscription_plans(id),
  amount numeric(12,2) not null check(amount>=0),
  currency_code text not null default 'BOB',
  provider text not null default 'veripagos',
  status text not null default 'pending'
    check(status in ('pending','approved','rejected','cancelled','expired','refunded')),
  provider_order_id text,
  qr_payload text,
  provider_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  paid_at timestamptz,
  expires_at timestamptz,
  cancelled_at timestamptz
);

create unique index if not exists driver_subscription_payments_provider_order_unique
on public.driver_subscription_payments(provider,provider_order_id)
where provider_order_id is not null;
create index if not exists driver_subscription_payments_driver_created_idx
on public.driver_subscription_payments(driver_id,created_at desc);
create index if not exists driver_subscription_payments_pending_idx
on public.driver_subscription_payments(status,expires_at) where status='pending';

create table if not exists public.driver_subscriptions (
  driver_id uuid primary key references public.driver_profiles(id) on delete cascade,
  plan_id bigint references public.driver_subscription_plans(id),
  status text not null default 'inactive'
    check(status in ('inactive','active','expired','suspended')),
  started_at timestamptz,
  expires_at timestamptz,
  last_payment_id bigint references public.driver_subscription_payments(id),
  updated_at timestamptz not null default now()
);
create index if not exists driver_subscriptions_status_expiry_idx
on public.driver_subscriptions(status,expires_at);

create table if not exists public.driver_subscription_history (
  id bigint generated by default as identity primary key,
  driver_id uuid not null references public.driver_profiles(id) on delete cascade,
  plan_id bigint references public.driver_subscription_plans(id),
  payment_id bigint references public.driver_subscription_payments(id),
  action text not null,
  previous_expires_at timestamptz,
  new_expires_at timestamptz,
  amount numeric(12,2),
  notes text,
  created_by uuid,
  created_at timestamptz not null default now()
);
create index if not exists driver_subscription_history_driver_created_idx
on public.driver_subscription_history(driver_id,created_at desc);

create table if not exists private.driver_subscription_provider_settings (
  id boolean primary key default true check(id),
  provider text not null default 'veripagos',
  api_base_url text,
  create_path text,
  status_path text,
  username text,
  password text,
  secret_key text,
  extra_config jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid
);
insert into private.driver_subscription_provider_settings(id) values(true)
on conflict(id) do nothing;
revoke all on private.driver_subscription_provider_settings from public, anon, authenticated;
grant select,insert,update on private.driver_subscription_provider_settings to service_role;

alter table public.driver_subscription_plans enable row level security;
alter table public.driver_subscription_settings enable row level security;
alter table public.driver_subscription_payments enable row level security;
alter table public.driver_subscriptions enable row level security;
alter table public.driver_subscription_history enable row level security;

create policy "driver subscription plans read" on public.driver_subscription_plans
for select to authenticated using(active or public.is_admin());
create policy "driver subscription plans admin manage" on public.driver_subscription_plans
for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "driver subscription settings read" on public.driver_subscription_settings
for select to authenticated using(true);
create policy "driver subscription settings admin manage" on public.driver_subscription_settings
for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "driver subscriptions own read" on public.driver_subscriptions
for select to authenticated using((select auth.uid())=driver_id or public.is_admin());
create policy "driver subscriptions admin manage" on public.driver_subscriptions
for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "driver subscription payments own read" on public.driver_subscription_payments
for select to authenticated using((select auth.uid())=driver_id or public.is_admin());
create policy "driver subscription payments admin manage" on public.driver_subscription_payments
for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "driver subscription history own read" on public.driver_subscription_history
for select to authenticated using((select auth.uid())=driver_id or public.is_admin());
create policy "driver subscription history admin manage" on public.driver_subscription_history
for all to authenticated using(public.is_admin()) with check(public.is_admin());

grant select on public.driver_subscription_plans,public.driver_subscription_settings,
  public.driver_subscriptions,public.driver_subscription_payments,
  public.driver_subscription_history to authenticated;
grant insert,update,delete on public.driver_subscription_plans,
  public.driver_subscription_settings,public.driver_subscriptions,
  public.driver_subscription_payments,public.driver_subscription_history to authenticated;
grant usage,select on all sequences in schema public to authenticated;
