-- Admin multizone payments, server-side filters, push analytics and partner settlements.
-- Additive/backward-compatible migration: existing service_zones.payment_provider and legacy RPCs stay intact.

alter table public.service_zones
  add column if not exists region_department text;

create table if not exists public.payment_method_catalog (
  provider_key text primary key,
  display_name text not null,
  provider_type text not null default 'gateway'
    check (provider_type in ('gateway','cash','transfer','wallet','card','other')),
  active boolean not null default true,
  credential_scope text not null default 'zone'
    check (credential_scope in ('zone','global','none')),
  supports_rides boolean not null default true,
  supports_delivery boolean not null default true,
  supports_subscriptions boolean not null default false,
  supports_wallet boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.payment_method_catalog enable row level security;

create table if not exists public.zone_payment_methods (
  id bigint generated by default as identity primary key,
  zone_id uuid not null references public.service_zones(id) on delete cascade,
  provider_key text not null references public.payment_method_catalog(provider_key) on update cascade,
  enabled boolean not null default true,
  use_rides boolean not null default true,
  use_delivery boolean not null default true,
  use_subscriptions boolean not null default false,
  use_wallet boolean not null default false,
  is_primary boolean not null default false,
  sort_order integer not null default 100,
  public_config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(zone_id, provider_key)
);

alter table public.zone_payment_methods enable row level security;

insert into public.payment_method_catalog(
  provider_key,display_name,provider_type,active,credential_scope,
  supports_rides,supports_delivery,supports_subscriptions,supports_wallet
)
values
  ('cash','Efectivo','cash',true,'none',true,true,true,true),
  ('veripagos_qr','QR Bolivia · VeriPagos','gateway',true,'global',true,true,true,true),
  ('mercado_pago','Mercado Pago','gateway',true,'zone',true,true,true,true),
  ('bank_transfer','Transferencia bancaria','transfer',true,'none',true,true,true,true),
  ('card','Tarjeta','card',true,'zone',true,true,true,true),
  ('wallet','Billetera Express','wallet',true,'none',true,true,true,true),
  ('santander','Santander','gateway',true,'zone',true,true,true,true),
  ('mach','MACH','gateway',true,'zone',true,true,true,true),
  ('tenpo','Tenpo','gateway',true,'zone',true,true,true,true)
on conflict (provider_key) do update
set display_name=excluded.display_name,
    provider_type=excluded.provider_type,
    credential_scope=excluded.credential_scope,
    supports_rides=excluded.supports_rides,
    supports_delivery=excluded.supports_delivery,
    supports_subscriptions=excluded.supports_subscriptions,
    supports_wallet=excluded.supports_wallet,
    updated_at=now();

insert into public.zone_payment_methods(
  zone_id,provider_key,enabled,use_rides,use_delivery,use_subscriptions,use_wallet,is_primary,sort_order
)
select
  z.id,
  coalesce(nullif(z.payment_provider,''),case when lower(z.country)='bolivia' then 'veripagos_qr' when lower(z.country)='chile' then 'mercado_pago' else 'cash' end),
  z.payment_enabled is not false,
  true,true,true,true,true,10
from public.service_zones z
where coalesce(nullif(z.payment_provider,''),case when lower(z.country)='bolivia' then 'veripagos_qr' when lower(z.country)='chile' then 'mercado_pago' else 'cash' end)
      in (select provider_key from public.payment_method_catalog)
on conflict (zone_id,provider_key) do nothing;

create unique index if not exists zone_payment_methods_one_primary_idx
  on public.zone_payment_methods(zone_id)
  where is_primary=true;

create index if not exists zone_payment_methods_zone_enabled_idx
  on public.zone_payment_methods(zone_id,enabled,sort_order);

create index if not exists ride_requests_zone_created_idx
  on public.ride_requests(zone_id,created_at desc);
create index if not exists trips_created_idx
  on public.trips(created_at desc);
create index if not exists delivery_requests_created_idx
  on public.delivery_requests(created_at desc);
create index if not exists users_last_zone_created_idx
  on public.users(last_zone_id,created_at desc);
create index if not exists driver_subscription_payments_zone_created_idx
  on public.driver_subscription_payments(zone_key,created_at desc);
create index if not exists payment_transactions_created_idx
  on public.payment_transactions(created_at desc);

create or replace function public.admin_payment_method_catalog_list()
returns jsonb
language plpgsql
stable
security definer
set search_path='public'
as $$
begin
  if not public.is_admin() then raise exception 'No autorizado'; end if;
  return (
    select coalesce(jsonb_agg(to_jsonb(c) order by c.display_name),'[]'::jsonb)
    from public.payment_method_catalog c
  );
end;
$$;

create or replace function public.admin_zone_payment_methods(p_zone_id uuid default null)
returns jsonb
language plpgsql
stable
security definer
set search_path='public'
as $$
begin
  if not public.is_admin() then raise exception 'No autorizado'; end if;
  return (
    select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'id',m.id,
          'zone_id',m.zone_id,
          'provider_key',m.provider_key,
          'display_name',c.display_name,
          'provider_type',c.provider_type,
          'credential_scope',c.credential_scope,
          'enabled',m.enabled,
          'use_rides',m.use_rides,
          'use_delivery',m.use_delivery,
          'use_subscriptions',m.use_subscriptions,
          'use_wallet',m.use_wallet,
          'is_primary',m.is_primary,
          'sort_order',m.sort_order,
          'public_config',m.public_config
        )
        order by m.sort_order,c.display_name
      ),
      '[]'::jsonb
    )
    from public.zone_payment_methods m
    join public.payment_method_catalog c on c.provider_key=m.provider_key
    where p_zone_id is null or m.zone_id=p_zone_id
  );
end;
$$;

create or replace function public.admin_upsert_zone_payment_method(
  p_zone_id uuid,
  p_provider_key text,
  p_enabled boolean default true,
  p_use_rides boolean default true,
  p_use_delivery boolean default true,
  p_use_subscriptions boolean default false,
  p_use_wallet boolean default false,
  p_is_primary boolean default false,
  p_sort_order integer default 100
)
returns bigint
language plpgsql
security definer
set search_path='public'
as $$
declare
  v_id bigint;
  v_provider text := lower(trim(coalesce(p_provider_key,'')));
begin
  if not public.is_admin() then raise exception 'No autorizado'; end if;
  if not exists(select 1 from public.service_zones where id=p_zone_id) then
    raise exception 'Zona inválida';
  end if;
  if not exists(select 1 from public.payment_method_catalog where provider_key=v_provider and active=true) then
    raise exception 'Método de pago inválido o inactivo';
  end if;

  if coalesce(p_is_primary,false) then
    update public.zone_payment_methods set is_primary=false,updated_at=now()
    where zone_id=p_zone_id and is_primary=true;
  end if;

  insert into public.zone_payment_methods(
    zone_id,provider_key,enabled,use_rides,use_delivery,use_subscriptions,use_wallet,is_primary,sort_order
  )
  values(
    p_zone_id,v_provider,coalesce(p_enabled,true),coalesce(p_use_rides,true),
    coalesce(p_use_delivery,true),coalesce(p_use_subscriptions,false),
    coalesce(p_use_wallet,false),coalesce(p_is_primary,false),coalesce(p_sort_order,100)
  )
  on conflict(zone_id,provider_key) do update set
    enabled=excluded.enabled,
    use_rides=excluded.use_rides,
    use_delivery=excluded.use_delivery,
    use_subscriptions=excluded.use_subscriptions,
    use_wallet=excluded.use_wallet,
    is_primary=excluded.is_primary,
    sort_order=excluded.sort_order,
    updated_at=now()
  returning id into v_id;

  -- Legacy mirror keeps the currently published mobile app compatible.
  if coalesce(p_is_primary,false) then
    update public.service_zones
    set payment_provider=v_provider,
        payment_enabled=coalesce(p_enabled,true),
        updated_at=now()
    where id=p_zone_id;
  end if;

  perform public.admin_log_action(
    'upsert_zone_payment_method','service_zones',p_zone_id::text,
    jsonb_build_object(
      'provider_key',v_provider,'enabled',p_enabled,'rides',p_use_rides,
      'delivery',p_use_delivery,'subscriptions',p_use_subscriptions,
      'wallet',p_use_wallet,'primary',p_is_primary
    )
  );
  return v_id;
end;
$$;

create or replace function public.admin_delete_zone_payment_method(
  p_zone_id uuid,
  p_provider_key text
)
returns boolean
language plpgsql
security definer
set search_path='public'
as $$
declare
  v_was_primary boolean := false;
begin
  if not public.is_admin() then raise exception 'No autorizado'; end if;
  select is_primary into v_was_primary
  from public.zone_payment_methods
  where zone_id=p_zone_id and provider_key=lower(trim(p_provider_key));

  delete from public.zone_payment_methods
  where zone_id=p_zone_id and provider_key=lower(trim(p_provider_key));

  if v_was_primary then
    update public.service_zones
    set payment_provider=null,payment_enabled=false,updated_at=now()
    where id=p_zone_id;
  end if;
  return found;
end;
$$;

create or replace function public.admin_upsert_zone_v2(
  p_id uuid,
  p_name text,
  p_city text,
  p_region_department text,
  p_country text,
  p_active boolean,
  p_center_latitude numeric,
  p_center_longitude numeric,
  p_radius_km numeric,
  p_zone_key text,
  p_currency_code text
)
returns uuid
language plpgsql
security definer
set search_path='public'
as $$
declare
  v_id uuid;
  v_key text;
begin
  if not public.is_admin() then raise exception 'No autorizado'; end if;
  if trim(coalesce(p_name,''))='' then raise exception 'Nombre requerido'; end if;
  if p_radius_km is null or p_radius_km<=0 then raise exception 'Radio inválido'; end if;

  v_key := lower(trim(coalesce(p_zone_key,'')));
  if v_key='' then
    v_key := lower(regexp_replace(
      translate(coalesce(nullif(trim(p_city),''),trim(p_name)),
      'ÁÉÍÓÚÜÑáéíóúüñ','AEIOUUNaeiouun'),
      '[^a-zA-Z0-9]+','_','g'
    ));
  end if;
  v_key := trim(both '_' from v_key);
  if v_key !~ '^[a-z0-9_]{2,60}$' then raise exception 'Clave de zona inválida'; end if;

  if p_id is null then
    insert into public.service_zones(
      name,city,region_department,country,active,center_latitude,center_longitude,
      radius_km,zone_key,currency_code
    )
    values(
      trim(p_name),nullif(trim(coalesce(p_city,'')),''),
      nullif(trim(coalesce(p_region_department,'')),''),
      coalesce(nullif(trim(coalesce(p_country,'')),''),'Bolivia'),
      coalesce(p_active,true),p_center_latitude,p_center_longitude,p_radius_km,
      v_key,upper(coalesce(nullif(trim(p_currency_code),''),'BOB'))
    )
    returning id into v_id;
  else
    update public.service_zones
    set name=trim(p_name),
        city=nullif(trim(coalesce(p_city,'')),''),
        region_department=nullif(trim(coalesce(p_region_department,'')),''),
        country=coalesce(nullif(trim(coalesce(p_country,'')),''),country),
        active=coalesce(p_active,true),
        center_latitude=p_center_latitude,
        center_longitude=p_center_longitude,
        radius_km=p_radius_km,
        zone_key=v_key,
        currency_code=upper(coalesce(nullif(trim(p_currency_code),''),currency_code)),
        updated_at=now()
    where id=p_id
    returning id into v_id;
  end if;
  if v_id is null then raise exception 'Zona no encontrada'; end if;
  return v_id;
end;
$$;

create or replace function public.admin_zone_list_v2()
returns jsonb
language plpgsql
stable
security definer
set search_path='public'
as $$
begin
  if not public.is_admin() then raise exception 'No autorizado'; end if;
  return (
    select coalesce(jsonb_agg(
      jsonb_build_object(
        'id',z.id,'name',z.name,'city',z.city,'region_department',z.region_department,
        'country',z.country,'active',z.active,'center_latitude',z.center_latitude,
        'center_longitude',z.center_longitude,'radius_km',z.radius_km,
        'zone_key',z.zone_key,'currency_code',z.currency_code,
        'payment_provider',z.payment_provider,'payment_enabled',z.payment_enabled,
        'payment_methods',coalesce((
          select jsonb_agg(jsonb_build_object(
            'provider_key',m.provider_key,'display_name',c.display_name,'enabled',m.enabled,
            'use_rides',m.use_rides,'use_delivery',m.use_delivery,
            'use_subscriptions',m.use_subscriptions,'use_wallet',m.use_wallet,
            'is_primary',m.is_primary,'sort_order',m.sort_order
          ) order by m.sort_order,c.display_name)
          from public.zone_payment_methods m
          join public.payment_method_catalog c on c.provider_key=m.provider_key
          where m.zone_id=z.id
        ),'[]'::jsonb)
      )
      order by z.country,z.city,z.name
    ),'[]'::jsonb)
    from public.service_zones z
  );
end;
$$;

create or replace function public.zone_payment_methods_for_context(
  p_zone_id uuid,
  p_context text
)
returns jsonb
language plpgsql
stable
security definer
set search_path='public'
as $$
declare
  v_context text := lower(trim(coalesce(p_context,'rides')));
begin
  if auth.uid() is null then raise exception 'Autenticación requerida'; end if;
  if v_context not in ('rides','delivery','subscriptions','wallet') then
    raise exception 'Contexto inválido';
  end if;
  return (
    select coalesce(jsonb_agg(
      jsonb_build_object(
        'provider_key',m.provider_key,
        'display_name',c.display_name,
        'provider_type',c.provider_type,
        'is_primary',m.is_primary,
        'sort_order',m.sort_order,
        'public_config',m.public_config
      )
      order by m.is_primary desc,m.sort_order,c.display_name
    ),'[]'::jsonb)
    from public.zone_payment_methods m
    join public.payment_method_catalog c on c.provider_key=m.provider_key
    where m.zone_id=p_zone_id
      and m.enabled=true and c.active=true
      and case v_context
        when 'rides' then m.use_rides
        when 'delivery' then m.use_delivery
        when 'subscriptions' then m.use_subscriptions
        when 'wallet' then m.use_wallet
      end
  );
end;
$$;

create or replace function public.admin_trip_list_v2(
  p_from timestamptz default null,
  p_to timestamptz default null,
  p_zone_id uuid default null,
  p_status text default null,
  p_limit integer default 100,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path='public'
as $$
begin
  if not public.is_admin() then raise exception 'No autorizado'; end if;
  return (
    select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc),'[]'::jsonb)
    from (
      select
        t.id,t.status,t.final_fare,t.payment_status,t.created_at,t.completed_at,
        pu.full_name as passenger_name,du.full_name as driver_name,
        rr.pickup_address,rr.destination_address,rr.category,rr.currency,rr.payment_method,
        rr.zone_id,z.name as zone_name,z.city,z.region_department,z.country
      from public.trips t
      left join public.ride_requests rr on rr.id=t.ride_request_id
      left join public.users pu on pu.id=t.passenger_id
      left join public.users du on du.id=t.driver_id
      left join public.service_zones z on z.id=rr.zone_id
      where (p_from is null or t.created_at>=p_from)
        and (p_to is null or t.created_at<p_to)
        and (p_zone_id is null or rr.zone_id=p_zone_id)
        and (p_status is null or p_status='' or t.status=p_status)
      order by t.created_at desc
      limit greatest(1,least(coalesce(p_limit,100),500))
      offset greatest(0,coalesce(p_offset,0))
    ) x
  );
end;
$$;

create or replace function public.admin_delivery_list_v2(
  p_from timestamptz default null,
  p_to timestamptz default null,
  p_status text default null,
  p_limit integer default 100,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path='public'
as $$
begin
  if not public.is_admin() then raise exception 'No autorizado'; end if;
  return (
    select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc),'[]'::jsonb)
    from (
      select
        d.id,d.status,d.proposed_fare,d.currency,d.payment_method,d.created_at,d.completed_at,
        cu.full_name as customer_name,du.full_name as courier_name,
        d.pickup_address,d.dropoff_address,d.package_type
      from public.delivery_requests d
      left join public.users cu on cu.id=d.customer_id
      left join public.users du on du.id=d.courier_id
      where (p_from is null or d.created_at>=p_from)
        and (p_to is null or d.created_at<p_to)
        and (p_status is null or p_status='' or d.status=p_status)
      order by d.created_at desc
      limit greatest(1,least(coalesce(p_limit,100),500))
      offset greatest(0,coalesce(p_offset,0))
    ) x
  );
end;
$$;

create or replace function public.admin_user_list_v3(
  p_zone_id uuid default null,
  p_city text default null,
  p_region_department text default null,
  p_country text default null,
  p_search text default null,
  p_limit integer default 100,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path='public','auth'
as $$
declare
  v_search text := lower(trim(coalesce(p_search,'')));
begin
  if not public.is_admin() then raise exception 'No autorizado'; end if;
  return (
    select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc),'[]'::jsonb)
    from (
      select
        u.id as user_id,u.full_name,au.email,u.phone,u.active_mode,u.account_status,
        d.approval_status as driver_status,coalesce(u.last_zone_id,d.zone_id) as zone_id,
        z.zone_key,z.name as zone_name,z.city,z.region_department,z.country,u.created_at,
        (
          exists(
            select 1 from public.audit_test_group_members m
            join public.audit_test_groups g on g.id=m.group_id
            where m.user_id=u.id and m.enabled=true and g.active=true
          )
          or lower(coalesce(au.email,'')) like 'qa-%@expressdelivery.pro'
          or lower(coalesce(u.full_name,'')) like 'qa %'
        ) as is_qa
      from public.users u
      left join auth.users au on au.id=u.id
      left join public.driver_profiles d on d.id=u.id
      left join public.service_zones z on z.id=coalesce(u.last_zone_id,d.zone_id)
      where (p_zone_id is null or z.id=p_zone_id)
        and (trim(coalesce(p_city,''))='' or lower(coalesce(z.city,''))=lower(trim(p_city)))
        and (trim(coalesce(p_region_department,''))='' or lower(coalesce(z.region_department,''))=lower(trim(p_region_department)))
        and (trim(coalesce(p_country,''))='' or lower(coalesce(z.country,''))=lower(trim(p_country)))
        and (
          v_search='' or
          lower(coalesce(u.full_name,'')) like '%'||v_search||'%' or
          lower(coalesce(au.email,'')) like '%'||v_search||'%' or
          lower(coalesce(u.phone,'')) like '%'||v_search||'%'
        )
      order by u.created_at desc
      limit greatest(1,least(coalesce(p_limit,100),500))
      offset greatest(0,coalesce(p_offset,0))
    ) x
  );
end;
$$;

create or replace function public.admin_payment_overview_v2(
  p_from timestamptz default null,
  p_to timestamptz default null,
  p_zone_id uuid default null,
  p_limit integer default 100,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path='public'
as $$
begin
  if not public.is_admin() then raise exception 'No autorizado'; end if;
  return jsonb_build_object(
    'summary',jsonb_build_object(
      'paid_count',(
        select count(*)
        from public.payment_transactions p
        left join public.trips t on t.id=p.trip_id
        left join public.ride_requests rr on rr.id=t.ride_request_id
        left join public.users payer on payer.id=p.payer_id
        where p.status='paid'
          and (p_from is null or coalesce(p.paid_at,p.created_at)>=p_from)
          and (p_to is null or coalesce(p.paid_at,p.created_at)<p_to)
          and (p_zone_id is null or coalesce(rr.zone_id,payer.last_zone_id)=p_zone_id)
      ),
      'pending_count',(
        select count(*)
        from public.payment_transactions p
        left join public.trips t on t.id=p.trip_id
        left join public.ride_requests rr on rr.id=t.ride_request_id
        left join public.users payer on payer.id=p.payer_id
        where p.status='pending'
          and (p_from is null or p.created_at>=p_from)
          and (p_to is null or p.created_at<p_to)
          and (p_zone_id is null or coalesce(rr.zone_id,payer.last_zone_id)=p_zone_id)
      ),
      'totals_by_currency',(
        select coalesce(jsonb_object_agg(currency,total),'{}'::jsonb)
        from (
          select p.currency,sum(p.amount)::numeric as total
          from public.payment_transactions p
          left join public.trips t on t.id=p.trip_id
          left join public.ride_requests rr on rr.id=t.ride_request_id
          left join public.users payer on payer.id=p.payer_id
          where p.status='paid'
            and (p_from is null or coalesce(p.paid_at,p.created_at)>=p_from)
            and (p_to is null or coalesce(p.paid_at,p.created_at)<p_to)
            and (p_zone_id is null or coalesce(rr.zone_id,payer.last_zone_id)=p_zone_id)
          group by p.currency
        ) sums
      ),
      'pending_by_currency',(
        select coalesce(jsonb_object_agg(currency,total),'{}'::jsonb)
        from (
          select p.currency,sum(p.amount)::numeric as total
          from public.payment_transactions p
          left join public.trips t on t.id=p.trip_id
          left join public.ride_requests rr on rr.id=t.ride_request_id
          left join public.users payer on payer.id=p.payer_id
          where p.status='pending'
            and (p_from is null or p.created_at>=p_from)
            and (p_to is null or p.created_at<p_to)
            and (p_zone_id is null or coalesce(rr.zone_id,payer.last_zone_id)=p_zone_id)
          group by p.currency
        ) sums
      )
    ),
    'recent',(
      select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc),'[]'::jsonb)
      from (
        select p.id,p.amount,p.currency,p.method,p.provider,p.status,p.created_at,p.paid_at,
               pu.full_name as payer_name,ru.full_name as payee_name,
               p.trip_id,p.delivery_id,
               coalesce(rr.zone_id,pu.last_zone_id) as zone_id,
               z.name as zone_name
        from public.payment_transactions p
        left join public.users pu on pu.id=p.payer_id
        left join public.users ru on ru.id=p.payee_id
        left join public.trips t on t.id=p.trip_id
        left join public.ride_requests rr on rr.id=t.ride_request_id
        left join public.service_zones z on z.id=coalesce(rr.zone_id,pu.last_zone_id)
        where (p_from is null or p.created_at>=p_from)
          and (p_to is null or p.created_at<p_to)
          and (p_zone_id is null or coalesce(rr.zone_id,pu.last_zone_id)=p_zone_id)
        order by p.created_at desc
        limit greatest(1,least(coalesce(p_limit,100),500))
        offset greatest(0,coalesce(p_offset,0))
      ) x
    )
  );
end;
$$;

create or replace function public.admin_subscription_payment_list_v2(
  p_zone_key text default null,
  p_from timestamptz default null,
  p_to timestamptz default null,
  p_status text default null,
  p_limit integer default 100,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path='public'
as $$
begin
  if not public.is_admin() then raise exception 'No autorizado'; end if;
  return (
    select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc),'[]'::jsonb)
    from (
      select p.*
      from public.driver_subscription_payments p
      where (trim(coalesce(p_zone_key,''))='' or p.zone_key=p_zone_key)
        and (p_from is null or p.created_at>=p_from)
        and (p_to is null or p.created_at<p_to)
        and (trim(coalesce(p_status,''))='' or p.status=p_status)
      order by p.created_at desc
      limit greatest(1,least(coalesce(p_limit,100),500))
      offset greatest(0,coalesce(p_offset,0))
    ) x
  );
end;
$$;

create table if not exists public.notification_campaigns (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  body text not null,
  audience text not null,
  zone_id uuid references public.service_zones(id) on delete set null,
  partner_id uuid references public.partner_organizations(id) on delete set null,
  recipients_targeted integer not null default 0,
  push_enabled_recipients integer not null default 0,
  created_by uuid,
  created_at timestamptz not null default now()
);
alter table public.notification_campaigns enable row level security;

alter table public.notifications
  add column if not exists campaign_id uuid references public.notification_campaigns(id) on delete set null;

create table if not exists public.notification_delivery_events (
  id bigint generated by default as identity primary key,
  notification_id uuid references public.notifications(id) on delete cascade,
  campaign_id uuid references public.notification_campaigns(id) on delete cascade,
  user_id uuid,
  channel text not null,
  event text not null,
  provider_status text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.notification_delivery_events enable row level security;
create index if not exists notification_delivery_events_campaign_idx
  on public.notification_delivery_events(campaign_id,created_at desc);
create index if not exists notifications_campaign_idx
  on public.notifications(campaign_id,user_id);

create or replace function public.admin_push_audience_estimate(
  p_audience text default 'drivers',
  p_zone_id uuid default null,
  p_partner_id uuid default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path='public'
as $$
declare
  v_targeted integer;
  v_push integer;
  v_native integer;
  v_web integer;
begin
  if not public.is_admin() then raise exception 'No autorizado'; end if;
  if p_audience not in ('drivers','passengers','all') then raise exception 'Audiencia inválida'; end if;

  with audience_users as (
    select u.id
    from public.users u
    left join public.driver_profiles dp on dp.id=u.id
    where u.account_status='active'
      and (
        p_audience='all'
        or (p_audience='drivers' and dp.id is not null and dp.approval_status='approved')
        or (p_audience='passengers' and (u.active_mode='passenger' or dp.id is null or dp.approval_status<>'approved'))
      )
      and (p_zone_id is null or coalesce(u.last_zone_id,dp.zone_id)=p_zone_id)
      and (
        p_partner_id is null or exists(
          select 1 from public.driver_partner_memberships m
          where m.driver_id=u.id and m.partner_id=p_partner_id and m.status='active'
        )
      )
  )
  select
    count(*)::int,
    count(*) filter(where exists(select 1 from public.native_push_tokens n where n.user_id=a.id and n.active=true))::int,
    count(*) filter(where exists(select 1 from public.push_subscriptions s where s.user_id=a.id and s.active=true))::int,
    count(*) filter(where
      exists(select 1 from public.native_push_tokens n where n.user_id=a.id and n.active=true)
      or exists(select 1 from public.push_subscriptions s where s.user_id=a.id and s.active=true)
    )::int
  into v_targeted,v_native,v_web,v_push
  from audience_users a;

  return jsonb_build_object(
    'recipients',coalesce(v_targeted,0),
    'push_enabled',coalesce(v_push,0),
    'native_enabled',coalesce(v_native,0),
    'web_enabled',coalesce(v_web,0)
  );
end;
$$;

create or replace function public.admin_send_announcement_v3(
  p_title text,
  p_body text,
  p_audience text default 'drivers',
  p_zone_id uuid default null,
  p_partner_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path='public'
as $$
declare
  v_campaign uuid;
  v_count integer := 0;
  v_push integer := 0;
  v_title text := trim(coalesce(p_title,''));
  v_body text := trim(coalesce(p_body,''));
begin
  if not public.is_admin() then raise exception 'No autorizado'; end if;
  if char_length(v_title)<1 or char_length(v_title)>90 then raise exception 'Título inválido'; end if;
  if char_length(v_body)<1 or char_length(v_body)>1000 then raise exception 'Mensaje inválido'; end if;
  if p_audience not in ('drivers','passengers','all') then raise exception 'Audiencia inválida'; end if;

  insert into public.notification_campaigns(
    title,body,audience,zone_id,partner_id,created_by
  )
  values(v_title,v_body,p_audience,p_zone_id,p_partner_id,auth.uid())
  returning id into v_campaign;

  with audience_users as (
    select u.id,
      (
        exists(select 1 from public.native_push_tokens n where n.user_id=u.id and n.active=true)
        or exists(select 1 from public.push_subscriptions s where s.user_id=u.id and s.active=true)
      ) as has_push
    from public.users u
    left join public.driver_profiles dp on dp.id=u.id
    where u.account_status='active'
      and (
        p_audience='all'
        or (p_audience='drivers' and dp.id is not null and dp.approval_status='approved')
        or (p_audience='passengers' and (u.active_mode='passenger' or dp.id is null or dp.approval_status<>'approved'))
      )
      and (p_zone_id is null or coalesce(u.last_zone_id,dp.zone_id)=p_zone_id)
      and (
        p_partner_id is null or exists(
          select 1 from public.driver_partner_memberships m
          where m.driver_id=u.id and m.partner_id=p_partner_id and m.status='active'
        )
      )
  ),
  inserted as (
    insert into public.notifications(user_id,title,body,type,metadata,campaign_id)
    select
      a.id,v_title,v_body,'admin_announcement',
      jsonb_strip_nulls(jsonb_build_object(
        'audience',p_audience,'zone_id',p_zone_id,'partner_id',p_partner_id,
        'campaign',true,'campaign_id',v_campaign
      )),
      v_campaign
    from audience_users a
    returning id,user_id
  )
  select
    (select count(*)::int from inserted),
    (select count(*)::int from audience_users where has_push)
  into v_count,v_push;

  update public.notification_campaigns
  set recipients_targeted=coalesce(v_count,0),
      push_enabled_recipients=coalesce(v_push,0)
  where id=v_campaign;

  perform public.admin_log_action(
    'send_announcement','notification_campaigns',v_campaign::text,
    jsonb_build_object(
      'title',v_title,'recipients',v_count,'push_enabled',v_push,
      'audience',p_audience,'zone_id',p_zone_id,'partner_id',p_partner_id
    )
  );

  return jsonb_build_object(
    'campaign_id',v_campaign,'recipients',coalesce(v_count,0),
    'push_enabled',coalesce(v_push,0),'audience',p_audience,
    'zone_id',p_zone_id,'partner_id',p_partner_id
  );
end;
$$;

create or replace function public.record_notification_event(
  p_notification_id uuid,
  p_event text
)
returns boolean
language plpgsql
security definer
set search_path='public'
as $$
declare
  v_user uuid;
  v_campaign uuid;
  v_event text := lower(trim(coalesce(p_event,'')));
begin
  if auth.uid() is null then raise exception 'Autenticación requerida'; end if;
  if v_event not in ('opened','read') then raise exception 'Evento inválido'; end if;

  select user_id,campaign_id into v_user,v_campaign
  from public.notifications
  where id=p_notification_id;

  if v_user is distinct from auth.uid() then raise exception 'No autorizado'; end if;

  if v_event='read' then
    update public.notifications set is_read=true
    where id=p_notification_id and user_id=auth.uid();
  end if;

  if not exists(
    select 1 from public.notification_delivery_events
    where notification_id=p_notification_id and user_id=auth.uid()
      and event=v_event and channel='app'
  ) then
    insert into public.notification_delivery_events(
      notification_id,campaign_id,user_id,channel,event,provider_status
    ) values(
      p_notification_id,v_campaign,auth.uid(),'app',v_event,'client'
    );
  end if;
  return true;
end;
$$;

create or replace function public.admin_notification_campaign_list(
  p_from timestamptz default null,
  p_to timestamptz default null,
  p_limit integer default 100
)
returns jsonb
language plpgsql
stable
security definer
set search_path='public'
as $
begin
  if not public.is_admin() then raise exception 'No autorizado'; end if;
  return (
    select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc),'[]'::jsonb)
    from (
      select
        c.id,c.title,c.body,c.audience,c.zone_id,z.name as zone_name,
        c.partner_id,p.name as partner_name,c.recipients_targeted,
        c.push_enabled_recipients,c.created_at,
        coalesce(ev.provider_accepted_users,0)::int as provider_accepted_users,
        coalesce(ev.provider_accepted_attempts,0)::int as provider_accepted_attempts,
        coalesce(ev.provider_invalid_attempts,0)::int as provider_invalid_attempts,
        coalesce(ev.opened_users,0)::int as opened_users,
        coalesce(nt.read_users,0)::int as read_users
      from public.notification_campaigns c
      left join public.service_zones z on z.id=c.zone_id
      left join public.partner_organizations p on p.id=c.partner_id
      left join lateral (
        select
          count(distinct e.notification_id) filter(where e.event='provider_accepted') as provider_accepted_users,
          count(*) filter(where e.event='provider_accepted') as provider_accepted_attempts,
          count(*) filter(where e.event='provider_invalid') as provider_invalid_attempts,
          count(distinct e.notification_id) filter(where e.event='opened') as opened_users
        from public.notification_delivery_events e
        where e.campaign_id=c.id
      ) ev on true
      left join lateral (
        select count(*) filter(where n.is_read=true) as read_users
        from public.notifications n
        where n.campaign_id=c.id
      ) nt on true
      where (p_from is null or c.created_at>=p_from)
        and (p_to is null or c.created_at<p_to)
      order by c.created_at desc
      limit greatest(1,least(coalesce(p_limit,100),500))
    ) x
  );
end;
$;

alter table public.partner_settlements
  add column if not exists payment_reference text,
  add column if not exists paid_by uuid;

create or replace function public.admin_partner_dashboard(
  p_partner_id uuid,
  p_from timestamptz default null,
  p_to timestamptz default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path='public'
as $$
declare
  v_partner jsonb;
begin
  if not public.is_admin() then raise exception 'No autorizado'; end if;

  select jsonb_build_object(
    'id',p.id,'name',p.name,'partner_code',p.partner_code,
    'organization_type',p.organization_type,'status',p.status,
    'commission_percent',p.commission_percent,'zone_id',p.zone_id,
    'zone_name',z.name,'currency_code',z.currency_code
  )
  into v_partner
  from public.partner_organizations p
  left join public.service_zones z on z.id=p.zone_id
  where p.id=p_partner_id;

  if v_partner is null then raise exception 'Aliado no encontrado'; end if;

  return jsonb_build_object(
    'partner',v_partner,
    'metrics',jsonb_build_object(
      'drivers_total',(
        select count(*) from public.driver_partner_memberships m
        where m.partner_id=p_partner_id and m.status='active'
      ),
      'drivers_online',(
        select count(*) from public.driver_partner_memberships m
        join public.driver_profiles d on d.id=m.driver_id
        where m.partner_id=p_partner_id and m.status='active' and d.online_status='online'
      ),
      'payments_count',(
        select count(*) from public.driver_subscription_payments pay
        where pay.partner_id=p_partner_id and pay.status='approved'
          and (p_from is null or coalesce(pay.paid_at,pay.created_at)>=p_from)
          and (p_to is null or coalesce(pay.paid_at,pay.created_at)<p_to)
      ),
      'gross_amount',(
        select coalesce(sum(pay.amount),0) from public.driver_subscription_payments pay
        where pay.partner_id=p_partner_id and pay.status='approved'
          and (p_from is null or coalesce(pay.paid_at,pay.created_at)>=p_from)
          and (p_to is null or coalesce(pay.paid_at,pay.created_at)<p_to)
      ),
      'commission_generated',(
        select coalesce(sum(pay.partner_commission_amount),0) from public.driver_subscription_payments pay
        where pay.partner_id=p_partner_id and pay.status='approved'
          and (p_from is null or coalesce(pay.paid_at,pay.created_at)>=p_from)
          and (p_to is null or coalesce(pay.paid_at,pay.created_at)<p_to)
      ),
      'commission_paid',(
        select coalesce(sum(s.commission_amount),0) from public.partner_settlements s
        where s.partner_id=p_partner_id and s.status='paid'
          and (p_from is null or coalesce(s.paid_at,s.created_at)>=p_from)
          and (p_to is null or coalesce(s.paid_at,s.created_at)<p_to)
      ),
      'commission_pending',(
        select greatest(
          coalesce((select sum(pay.partner_commission_amount) from public.driver_subscription_payments pay
                    where pay.partner_id=p_partner_id and pay.status='approved'),0)
          -
          coalesce((select sum(s.commission_amount) from public.partner_settlements s
                    where s.partner_id=p_partner_id and s.status='paid'),0),
          0
        )
      )
    ),
    'payments',public.admin_partner_payment_list(p_partner_id,100),
    'settlements',public.admin_partner_settlement_list(p_partner_id)
  );
end;
$$;

create or replace function public.admin_mark_partner_settlement_paid(
  p_settlement_id bigint,
  p_reference text default null,
  p_notes text default null
)
returns boolean
language plpgsql
security definer
set search_path='public'
as $$
begin
  if not public.is_admin() then raise exception 'No autorizado'; end if;

  update public.partner_settlements
  set status='paid',
      paid_at=now(),
      paid_by=auth.uid(),
      payment_reference=nullif(trim(coalesce(p_reference,'')),''),
      notes=coalesce(nullif(trim(coalesce(p_notes,'')),''),notes)
  where id=p_settlement_id and status<>'paid';

  if not found then return false; end if;

  perform public.admin_log_action(
    'partner_settlement_paid','partner_settlements',p_settlement_id::text,
    jsonb_build_object('reference',p_reference)
  );
  return true;
end;
$$;

-- Lock down admin/security-definer RPCs from anon/PUBLIC while keeping signed-in admin calls working.
revoke all on table public.payment_method_catalog from anon, public;
revoke all on table public.zone_payment_methods from anon, public;
revoke all on table public.notification_campaigns from anon, public;
revoke all on table public.notification_delivery_events from anon, public;

revoke execute on function public.admin_payment_method_catalog_list() from anon, public;
revoke execute on function public.admin_zone_payment_methods(uuid) from anon, public;
revoke execute on function public.admin_upsert_zone_payment_method(uuid,text,boolean,boolean,boolean,boolean,boolean,boolean,integer) from anon, public;
revoke execute on function public.admin_delete_zone_payment_method(uuid,text) from anon, public;
revoke execute on function public.admin_upsert_zone_v2(uuid,text,text,text,text,boolean,numeric,numeric,numeric,text,text) from anon, public;
revoke execute on function public.admin_zone_list_v2() from anon, public;
revoke execute on function public.admin_trip_list_v2(timestamptz,timestamptz,uuid,text,integer,integer) from anon, public;
revoke execute on function public.admin_delivery_list_v2(timestamptz,timestamptz,text,integer,integer) from anon, public;
revoke execute on function public.admin_user_list_v3(uuid,text,text,text,text,integer,integer) from anon, public;
revoke execute on function public.admin_payment_overview_v2(timestamptz,timestamptz,uuid,integer,integer) from anon, public;
revoke execute on function public.admin_subscription_payment_list_v2(text,timestamptz,timestamptz,text,integer,integer) from anon, public;
revoke execute on function public.admin_push_audience_estimate(text,uuid,uuid) from anon, public;
revoke execute on function public.admin_send_announcement_v3(text,text,text,uuid,uuid) from anon, public;
revoke execute on function public.admin_notification_campaign_list(timestamptz,timestamptz,integer) from anon, public;
revoke execute on function public.admin_partner_dashboard(uuid,timestamptz,timestamptz) from anon, public;
revoke execute on function public.admin_mark_partner_settlement_paid(bigint,text,text) from anon, public;
revoke execute on function public.record_notification_event(uuid,text) from anon, public;
revoke execute on function public.zone_payment_methods_for_context(uuid,text) from anon, public;

grant execute on function public.admin_payment_method_catalog_list() to authenticated;
grant execute on function public.admin_zone_payment_methods(uuid) to authenticated;
grant execute on function public.admin_upsert_zone_payment_method(uuid,text,boolean,boolean,boolean,boolean,boolean,boolean,integer) to authenticated;
grant execute on function public.admin_delete_zone_payment_method(uuid,text) to authenticated;
grant execute on function public.admin_upsert_zone_v2(uuid,text,text,text,text,boolean,numeric,numeric,numeric,text,text) to authenticated;
grant execute on function public.admin_zone_list_v2() to authenticated;
grant execute on function public.admin_trip_list_v2(timestamptz,timestamptz,uuid,text,integer,integer) to authenticated;
grant execute on function public.admin_delivery_list_v2(timestamptz,timestamptz,text,integer,integer) to authenticated;
grant execute on function public.admin_user_list_v3(uuid,text,text,text,text,integer,integer) to authenticated;
grant execute on function public.admin_payment_overview_v2(timestamptz,timestamptz,uuid,integer,integer) to authenticated;
grant execute on function public.admin_subscription_payment_list_v2(text,timestamptz,timestamptz,text,integer,integer) to authenticated;
grant execute on function public.admin_push_audience_estimate(text,uuid,uuid) to authenticated;
grant execute on function public.admin_send_announcement_v3(text,text,text,uuid,uuid) to authenticated;
grant execute on function public.admin_notification_campaign_list(timestamptz,timestamptz,integer) to authenticated;
grant execute on function public.admin_partner_dashboard(uuid,timestamptz,timestamptz) to authenticated;
grant execute on function public.admin_mark_partner_settlement_paid(bigint,text,text) to authenticated;
grant execute on function public.record_notification_event(uuid,text) to authenticated;
grant execute on function public.zone_payment_methods_for_context(uuid,text) to authenticated;
