-- Harden Firebase free-tier protection by using a rolling 24-hour window.
-- This is deliberately more conservative than a calendar-day reset so Express
-- cannot accidentally exceed Google's 10 free SMS because of timezone boundaries.

create table if not exists public.phone_otp_provider_reservations (
  id bigint generated by default as identity primary key,
  provider_key text not null,
  reserved_at timestamptz not null default now()
);

create index if not exists phone_otp_provider_reservations_lookup_idx
  on public.phone_otp_provider_reservations(provider_key, reserved_at desc);

alter table public.phone_otp_provider_reservations enable row level security;

create or replace function public.reserve_phone_otp_daily_slot(
  p_provider_key text,
  p_limit integer default 10
)
returns jsonb
language plpgsql
security invoker
set search_path=public
as $$
declare
  v_key text:=trim(coalesce(p_provider_key,''));
  v_limit integer:=coalesce(p_limit,10);
  v_now timestamptz:=now();
  v_used integer:=0;
  v_oldest timestamptz;
  v_retry_after integer:=0;
begin
  if v_key='' or length(v_key)>180 then
    raise exception 'provider_key inválido';
  end if;
  if v_limit<1 or v_limit>100 then
    raise exception 'límite inválido';
  end if;

  -- Serialize reservations per provider/project so concurrent OTP requests
  -- cannot both claim the same final free slot.
  perform pg_advisory_xact_lock(hashtextextended(v_key,0));

  select count(*)::integer, min(reserved_at)
    into v_used, v_oldest
  from public.phone_otp_provider_reservations
  where provider_key=v_key
    and reserved_at > v_now - interval '24 hours';

  if v_used >= v_limit then
    if v_oldest is not null then
      v_retry_after:=greatest(
        1,
        ceil(extract(epoch from (v_oldest + interval '24 hours' - v_now)))::integer
      );
    end if;

    return jsonb_build_object(
      'reserved',false,
      'provider_key',v_key,
      'used',v_used,
      'limit',v_limit,
      'window_hours',24,
      'retry_after_seconds',v_retry_after
    );
  end if;

  insert into public.phone_otp_provider_reservations(provider_key,reserved_at)
  values(v_key,v_now);

  v_used:=v_used+1;

  return jsonb_build_object(
    'reserved',true,
    'provider_key',v_key,
    'used',v_used,
    'remaining',greatest(v_limit-v_used,0),
    'limit',v_limit,
    'window_hours',24
  );
end;
$$;

comment on table public.phone_otp_provider_reservations is
  'Server-only rolling 24-hour reservations used to conservatively cap Firebase Phone Auth SMS.';
